//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace FS.Abp.CodingManagement.Coding
{
    public partial class EfCoreCodesTreeRepository : ICodesTreeRepository
    {
        public async Task<Codes> GetDefinitionAsync(string definitionNo)
        {
            var results = await this.Where(x => x.No == definitionNo && x.ParentId == null)
                .Include(e => e.CodeList)
                .ToListAsync().ConfigureAwait(false);
            return results.Single();
        }
    }
}
