//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
namespace FS.Abp.CodingManagement.Coding.Dtos
{
    public partial class CodesDto
    {
    }
    public partial class CodesWithDetailsDto
    {
    }
    public partial class CodesCreateInput
    {
    }
    public partial class CodesUpdateInput
    {
    }
    public partial class CodesGetListInput
    {
    }
    public partial class CodesMoveInput
    {
    }
    public class UpdateListInput : CodesUpdateInput
    {
        public Guid Id { get; set; }
    }
}
