//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Abp.CodingManagement.Versions
{
    public partial interface IVersionCrudAppService : 
        FS.Abp.Application.Services.ICrudAppService<FS.Abp.CodingManagement.Versions.Dtos.VersionWithDetailsDto, Guid, FS.Abp.CodingManagement.Versions.Dtos.VersionGetListInput, FS.Abp.CodingManagement.Versions.Dtos.VersionCreateInput, FS.Abp.CodingManagement.Versions.Dtos.VersionUpdateInput>
    {

    }
}
