//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Abp.CodingManagement.Coding.Dtos
{
    public partial class CodeConfigAutoMapperProfile : Profile
    {
        public CodeConfigAutoMapperProfile()
        {
            CreateMap<FS.Abp.CodingManagement.Coding.CodeConfig, CodeConfigDto>()
            .ReverseMap();
        
            CreateMap<FS.Abp.CodingManagement.Coding.CodeConfig, CodeConfigWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
