//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Abp.CodingManagement.Coding.Dtos
{
    public partial class CodesCreateInputValidator : AbstractValidator<CodesCreateInput>
    {
        public CodesCreateInputValidator()
        {
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.Description)
                ;
            RuleFor(p => p.Code)
                ;
            RuleFor(p => p.DefinitionId)
                ;
            RuleFor(p => p.ParentId)
                ;
            RuleFor(p => p.Enable)
                .NotNull()
                ;
            RuleFor(p => p.Config)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class CodesUpdateInputValidator : AbstractValidator<CodesUpdateInput>
    {
        public CodesUpdateInputValidator()
        {
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.Description)
                ;
            RuleFor(p => p.Code)
                ;
            RuleFor(p => p.DefinitionId)
                ;
            RuleFor(p => p.ParentId)
                ;
            RuleFor(p => p.Enable)
                .NotNull()
                ;
            RuleFor(p => p.Config)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
