//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Abp.CodingManagement.Versions.Dtos
{
    public partial class VersionDto : Volo.Abp.Application.Dtos.FullAuditedEntityDto<Guid>
    {
        public string ProviderName { get; set; }

        public string ProviderKey { get; set; }

        public string Description { get; set; }

        public class PrimaryKey
        {
            public System.Guid Id { get; set; }
    
        }

    }
    public partial class VersionWithDetailsDto : VersionDto
    {
    }
    public partial class VersionCreateInput
    {
        public string ProviderName { get; set; }

        public string ProviderKey { get; set; }

        public string Description { get; set; }

    }
    public partial class VersionUpdateInput
    {
        public string ProviderName { get; set; }

        public string ProviderKey { get; set; }

        public string Description { get; set; }

    }
    public partial class VersionGetListInput : SearchResultRequestDto
    {
    }
}
