//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Abp.CodingManagement.Coding
{
    public partial interface ICodesTreeAppService : 
        FS.Abp.Application.Services.ICrudAppService<FS.Abp.CodingManagement.Coding.Dtos.CodesWithDetailsDto, Guid, FS.Abp.CodingManagement.Coding.Dtos.CodesGetListInput, FS.Abp.CodingManagement.Coding.Dtos.CodesCreateInput, FS.Abp.CodingManagement.Coding.Dtos.CodesUpdateInput>
    {

    }
}
