//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.Abp.CodingManagement.EntityFrameworkCore
{
    public static class CodingManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureCodingManagement(
            this ModelBuilder builder,
            Action<CodingManagementModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new CodingManagementModelBuilderConfigurationOptions(
                CodingManagementDbProperties.DbTablePrefix,
                CodingManagementDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            builder.Ignore<FS.Abp.CodingManagement.Versions.Versions>();
            builder.ApplyConfiguration<FS.Abp.CodingManagement.Coding.Codes>(new FS.Abp.CodingManagement.Coding.CodesConfiguration(options));
            builder.ApplyConfiguration<FS.Abp.CodingManagement.Versions.Version>(new FS.Abp.CodingManagement.Versions.VersionConfiguration(options));
        }
    }
}
