//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Abp.CodingManagement.Versions
{
    public partial class VersionCrudAppService : 
        FS.Abp.Application.Services.CrudAppService<FS.Abp.CodingManagement.Versions.Version, FS.Abp.CodingManagement.Versions.Dtos.VersionWithDetailsDto, Guid, FS.Abp.CodingManagement.Versions.Dtos.VersionGetListInput, FS.Abp.CodingManagement.Versions.Dtos.VersionCreateInput, FS.Abp.CodingManagement.Versions.Dtos.VersionUpdateInput>,
        IVersionCrudAppService
    {
        private readonly IVersionRepository _repository;

        public VersionCrudAppService(IVersionRepository repository) : base(repository)
        {
            this._repository = repository;
        }



    }
}
