//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Abp.CodingManagement.Coding.Dtos
{
    public partial class CodeConfigDto
    {
        public List<string> ExcludeSettingsGroups { get; set; }

        public List<string> IncludeSettingsGroups { get; set; }

    }
    public partial class CodeConfigWithDetailsDto : CodeConfigDto
    {
    }
}
