//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Abp.CodingManagement.Coding.Dtos
{
    public partial class CodesDto : Volo.Abp.Application.Dtos.AuditedEntityDto<Guid>
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? DefinitionId { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Abp.CodingManagement.Coding.Dtos.CodeConfigDto Config { get; set; }

        public class PrimaryKey
        {
            public System.Guid Id { get; set; }
    
        }

        public class DefinitionForeignKey
        {
            public System.Guid? DefinitionId { get; set; }
    
        }
        public class ParentForeignKey
        {
            public System.Guid? ParentId { get; set; }
    
        }
    }
    public partial class CodesWithDetailsDto : CodesDto
    {
        public List<CodesDto> CodeList { get; set; }

        public CodesDto Definition { get; set; }

        public List<CodesDto> Children { get; set; }

        public CodesDto Parent { get; set; }

    }
    public partial class CodesCreateInput
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? DefinitionId { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Abp.CodingManagement.Coding.Dtos.CodeConfigDto Config { get; set; }

    }
    public partial class CodesUpdateInput
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? DefinitionId { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Abp.CodingManagement.Coding.Dtos.CodeConfigDto Config { get; set; }

    }
    public partial class CodesGetListInput : SearchResultRequestDto
    {
    }
}
