//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Abp.CodingManagement.Versions.Dtos
{
    public partial class VersionCreateInputValidator : AbstractValidator<VersionCreateInput>
    {
        public VersionCreateInputValidator()
        {
            RuleFor(p => p.ProviderName)
                ;
            RuleFor(p => p.ProviderKey)
                ;
            RuleFor(p => p.Description)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class VersionUpdateInputValidator : AbstractValidator<VersionUpdateInput>
    {
        public VersionUpdateInputValidator()
        {
            RuleFor(p => p.ProviderName)
                ;
            RuleFor(p => p.ProviderKey)
                ;
            RuleFor(p => p.Description)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
