//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Abp.CodingManagement.Versions.Dtos
{
    public partial class VersionsAutoMapperProfile : Profile
    {
        public VersionsAutoMapperProfile()
        {
            CreateMap<FS.Abp.CodingManagement.Versions.Versions, VersionsDto>()
            .ReverseMap();
        
            CreateMap<FS.Abp.CodingManagement.Versions.Versions, VersionsWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
