//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Linq.Expressions;

namespace FS.Abp.CodingManagement.Versions
{
    public partial class EfCoreVersionRepository : 
        EfCoreRepository<FS.Abp.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext,FS.Abp.CodingManagement.Versions.Version,Guid>,
        IVersionRepository
    {
        public EfCoreVersionRepository(IDbContextProvider<FS.Abp.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext> dbContextProvider)
            : base(dbContextProvider) { }
    }
}
