//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.290.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace Volo.Abp.Localization
{
    public static partial class LocalizationResourceExtensions
    {
        public static LocalizationResource AddCodingManagementDomainLocalizations(this LocalizationResource resource)
        {
            return resource
                .AddVirtualJson(@"/_Generated/Localization/CodingManagement");
        }
    }
}
