//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.Abp.CodingManagement.Localization;

namespace FS.Abp.CodingManagement.Core
{
    public class CorePermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var CoreGroup = context.AddGroup(CorePermissionNames.GroupName);

            var Coding = CoreGroup.AddPermission(CorePermissionNames.Coding.Default);
            Coding.AddChild(CorePermissionNames.Coding.DevelopPage);
        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<CodingManagementResource>(name);
        }
    }
}
