//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Linq.Expressions;

namespace FS.Abp.CodingManagement.Coding
{
    public partial class EfCoreCodesTreeRepository : 
        FS.Abp.Trees.EfCoreTreeRepository<FS.Abp.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext,FS.Abp.CodingManagement.Coding.Codes>,
        ICodesTreeRepository
    {
        public EfCoreCodesTreeRepository(IDbContextProvider<FS.Abp.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override IQueryable<FS.Abp.CodingManagement.Coding.Codes> WithDetails()
        {
            return base.WithDetails(new Expression<Func<FS.Abp.CodingManagement.Coding.Codes, object>>[] 
            {
                x => x.CodeList,
                x => x.Definition,
                x => x.Children,
                x => x.Parent
            });
        }
    }
}
