//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Data;

namespace FS.Abp.CodingManagement.Coding
{
    public partial class CodeConfig 
    {

        public CodeConfig()
        {
            OnCreated();
        }
        public virtual List<String> ExcludeSettingsGroups
        {
            get;
            set;
        } 
        public virtual List<String> IncludeSettingsGroups
        {
            get;
            set;
        } 


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
