//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.221.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.Abp.CodingManagement.Versions
{
    public partial interface IVersionRepository : 
        Volo.Abp.Domain.Repositories.IRepository<FS.Abp.CodingManagement.Versions.Version,Guid>
    {

    }
}
